version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification-system
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
  app:
    build: .
    depends_on:
      - db
      - mailpit
    environment:
      APPLICATION_PORT: 4000
      DSN: app:app@tcp(db:3306)/notification-system?charset=utf8mb4&parseTime=True&loc=Local
      MAIL_DRIVER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USER: ""
      MAIL_PASSWORD: ""
      SMS_DRIVER: log
      PUSH_DRIVER: log
      BASIC_AUTH_USERNAME: ""
      BASIC_AUTH_PASSWORD: ""
    ports:
      - "4000:4000"
volumes:
  db_data:
